
title: Kendama
email: your-email@example.com
description: dsdsds
destination: docs

baseurl: "/su-css-advanced-2019"
url:  
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdow
plugins:
  - jekyll-feed


exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal